name: 4_workflows
on:
  workflow_run:
    workflows: ['start_workflows']
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install dependency
        run: |
          npm install
      - run: node scan.js
