  
name: start_workflows
on:
  schedule:
    - cron:  '2,12,22,32,42,52 * * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ['1_workflows']
    types: 
      - completed
jobs:
  build:
    steps:
      - name: Start other job
        run: echo "Start other job"
